### ISSUE TITLE
安装 hexo-abbrlink 插件后文件路径错误

### ISSUE THREAD

**Issue by MHuiG** [NaturalSelectionLabs/hexo-deployer-rss3#49]
安装了 hexo-abbrlink 插件,运行hexo d 后报错.

_config.yml
```yaml
# hexo-abbrlink
# https://github.com/rozbo/hexo-abbrlink
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
deploy: # 所有部署器的根配置块
- type: rss3
  endpoint: https://hub.rss3.io # 一个 RSS3 Hub 的链接
  privateKey: xx # 您的私钥，64字节。
  ipfs: # ipfs 相关的配置
    deploy: true # 是否部署到 IPFS
    gateway: pinata # IPFS API 网关
    api: # IPFS 网关相关的验证内容
      key: xx
      secret: xx
```

报错信息(截取一部分):

```sh
INFO  Deploying: rss3
Start processing XXXXX ...
ReadStream {
  fd: null,
  path: 'public\\posts\\xxxxxxxxx.html\\index.html',
  flags: 'r',
  mode: 438,
  start: undefined,
  end: Infinity,
  pos: undefined,
  bytesRead: 0,
  closed: false,
  _readableState: ReadableState {
.............................................
  [Symbol(kIsPerformingIO)]: false,
  [Symbol(kCapture)]: false
}
[Error: ENOENT: no such file or directory, open 'xxxxxx\blog-source\public\posts\xxxxxxxxx.html\index.html'] 
.............................................
}
FATAL {
  err: TypeError: Cannot read properties of undefined (reading 'data')
      at parseToRSS3Item (xxxxxx\hexo-deployer-rss3\lib\deployer.js:192:21)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Hexo.module.exports (xxxxxx\hexo-deployer-rss3\lib\deployer.js:240:28)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

目标文件是 xxxxxx\blog-source\public\posts\xxxxxxxxx.html  并不是 xxxxxx\blog-source\public\posts\xxxxxxxxx.html\index.html

https://github.com/NaturalSelectionLabs/hexo-deployer-rss3/blob/4898d85266b0fd4d1a98d7a6eca2a9c149c1616f/lib/deployer.js#L159

除了这个错误,还有一些问题:

- 如何查看和订阅已经提交的数据? (除了https://hub.rss3.io/0xXXXXXXXXXXXXXXXXXXXXX   "@version":"rss3.io/version/v0.1.1" )
- 如何删除已经提交的数据?
